Repository KUSITMS-29th-TEAM-B/Backend, pull requests merged in 2024-05, with the labels that each got.

#8 Feat: CI / CD 환경 구축
  .github/workflows/CD-dev.yml
  .github/workflows/CI-dev.yml
  .gitignore
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/ApiModuleApplication.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/auth/presentation/config/SecurityConfig.kt
  Api-Module/src/main/resources/application.properties
  Api-Module/src/main/resources/application.yml
  Dockerfile
  build.gradle.kts
  docker-compose.yml
  scripts/deploy.sh
Labels: 🌏 Deploy&Infra, 🦦 용현

#13 feat: 구글 소셜 로그인 기능 구현
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/ApiModuleApplication.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/auth/application/exception/AuthException.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/auth/application/service/client/GoogleOAuthClient.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/auth/application/service/command/handler/impl/GoogleOAuthHandler.kt
  Api-Module/src/main/resources/application.yml
Labels: ✨ Feature, 🦦 용현

#16 chore: 의존성 관리(#15)
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  Api-Module/build.gradle.kts
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/auth/application/service/command/handler/impl/GoogleOAuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/auth/application/service/command/handler/impl/KakaoOAuthHandler.kt
  Domain-Module/build.gradle.kts
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/global/.gitkeep
  Infrastructure-Module/Module-Info.md
  Infrastructure-Module/build.gradle.kts
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/client/GoogleOAuthClient.kt
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/client/KakaoOAuthClient.kt
  build.gradle.kts
Labels: ⚙ Setting, 🐳 세은

#24 feat: 경험, 역량 키워드, 태그 엔티티 구성
  Api-Module/src/main/resources/application.yml
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/util/TransactionUtils.kt
  Infrastructure-Module/build.gradle.kts
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/.gitkeep
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/common/config/PersistenceConfig.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/common/global/BaseTimeEntity.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/experience/jpa/entity/ExperienceContentJpaEntity.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/experience/jpa/entity/ExperienceJpaEntity.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/experience/jpa/entity/ExperienceStrongPointJpaEntity.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/experience/jpa/entity/ExperienceTagJpaEntity.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/strongpoint/jpa/entity/StrongPointJpaEntity.java
  Infrastructure-Module/src/main/kotlin/com/bamyanggang/infrastructuremodule/persistence/tag/jpa/entity/TagJpaEntity.java
  Infrastructure-Module/src/main/resources/application-db.yml
Labels: ✨ Feature, 🦦 용현

#27 feat : 회원 가입 API 추가
  Api-Module/build.gradle.kts
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/Register.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/TokenService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/command/AuthInvoker.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/command/handler/AuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/command/handler/impl/GoogleOAuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/command/handler/impl/KakaoOAuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/security/JwtAuthenticationToken.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/security/filter/JwtAuthenticationFilter.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/security/filter/JwtEntryPoint.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/ErrorResponse.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/ExceptionHandler.kt
  Domain-Module/build.gradle.kts
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/common/entity/AggregateRoot.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/common/entity/DomainEntity.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/Token.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/User.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/enums/DesiredJob.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/enums/JobSearchStatus.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/enums/SocialLoginProvider.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/TokenRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/UserRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/global/entity/AggregateRoot.kt
  Infrastructure-Module/build.gradle.kts
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/client/GoogleOAuthClient.kt
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/client/KakaoOAuthClient.kt
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/persistence/exception/PersistenceException.kt
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/persistence/user/TokenRepositoryImpl.java
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/persistence/user/UserRepositoryImpl.kt
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/persistence/user/jpa/entity/UserJpaEntity.java
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/persistence/user/jpa/repository/UserJpaRepository.java
  Infrastructure-Module/src/main/java/com/bamyanggang/infrastructuremodule/persistence/user/mapper/UserMapper.java
  Support-Module/build.gradle.kts
  Support-Module/src/main/kotlin/com/bamyanggang/supportmodule/jwt/PrivateClaims.kt
  Support-Module/src/main/kotlin/com/bamyanggang/supportmodule/jwt/TokenExtractor.kt
  Support-Module/src/main/kotlin/com/bamyanggang/supportmodule/uuid/UuidCreator.kt
  build.gradle.kts
Labels: ✨ Feature, 🐳 세은

#30 feat : 회원가입 API 로직 개발, API 명세 작성
  Api-Module/.gitignore
  Api-Module/build.gradle.kts
  Api-Module/src/docs/asciidoc/Auth.adoc
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/SocialLogin.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/security/filter/JwtAuthenticationFilter.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthControllerTest.kt
  Api-Module/src/testFixtures/kotlin/com/bamyanggang/apimodule/BaseRestDocsTest.kt
  Api-Module/src/testFixtures/kotlin/com/bamyanggang/apimodule/FilterConfig.kt
  Api-Module/src/testFixtures/kotlin/com/bamyanggang/apimodule/RestDocsConfig.kt
  Common-Module/src/testFixtures/kotlin/com/bamyanggang/commonmodule/fixture/FixtureMonkeyUtils.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/User.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/common/exception/PersistenceException.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/TokenRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/TokenJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/UserJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/TokenJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/UserJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/mapper/UserMapper.java
  build.gradle.kts
Labels: ✨ Feature, ✅ Test, 🐳 세은

#36 feat: 경험, 태그, 역량 키워드 도메인 설계
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/config/SecurityConfig.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/CustomException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/Experience.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/ExperienceContent.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/StrongPoint.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/Tag.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/repository/ExperienceRepository.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/common/exception/PersistenceException.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/ExperienceRepositoryImpl.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceContentJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceStrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceTagJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/StrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/TagJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/repository/ExperienceContentJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/repository/ExperienceJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/repository/ExperienceTagJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/repository/StrongPointJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/repository/TagJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceContentMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/StrongPointMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/TagMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.kt
Labels: ✨ Feature, 🦦 용현

#37 refactor : 회원가입, 로그인 코드 리팩터링(#35)
  .deploy/docker-compose-dev.yml
  .github/workflows/CD-dev.yml
  Api-Module/src/docs/asciidoc/User.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/ProfileImageResponse.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/Register.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/ProfileImageGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/command/AuthInvoker.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/AuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/AuthHandlerManager.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/config/AuthHandlerConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/impl/GoogleOAuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/impl/KakaoOAuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/security/filter/JwtAuthenticationFilter.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserControllerTest.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/ExceptionHandler.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/User.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/vo/ProfileImage.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/enums/DesiredJob.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/enums/JobSearchStatus.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/ProfileImageRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/ProfileImageReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserAppender.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/ProfileImageRepositoryImpl.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/ProfileImageJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/UserJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/ProfileImageJpaRepository.java
  Support-Module/Jwt/src/main/resources/application-jwt.yml
Labels: 🔨 Refactor, ✅ Test, 🐳 세은

#43 refactor : 코드 병합 수정(#35)
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/SecurityUtils.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/UserUtils.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/CustomException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/UserRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserReader.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/UserJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/UserJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/mapper/UserMapper.java
Labels: 🔨 Refactor, ✨ Feature, 🐳 세은

#49 feat : 마이페이지 API 구현 (#48)
  Api-Module/src/docs/asciidoc/User.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/UserSecurityUtil.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/UserUtils.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/UserInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserInfoUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/config/CorsConfig.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/User.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserModifier.kt
Labels: ✨ Feature, ✅ Test, 🐳 세은

#55 feat : 토큰 재발급 API, 로그아웃 API 구현
  Api-Module/src/docs/asciidoc/Auth.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/Logout.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/ProfileImage.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/ProfileImageResponse.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/Reissue.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/ProfileImageGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserInfoUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthControllerTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/Token.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/TokenRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenAppender.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/TokenRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/TokenJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/TokenJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/mapper/UserMapper.java
  Support-Module/Jwt/build.gradle.kts
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/DefaultJwtRegistry.kt
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/JwtProvider.kt
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/JwtRegistry.kt
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/exception/JwtException.kt
  Support-Module/cache/build.gradle.kts
  Support-Module/cache/src/main/kotlin/com/bamyanggang/cache/CacheManager.kt
  Support-Module/lock/build.gradle.kts
  Support-Module/lock/src/main/kotlin/com/bamyanggang/lock/LockManager.kt
  settings.gradle.kts
Labels: ✨ Feature, 🐳 세은

#50 feat: 역량 키워드 등록 API 구현(#46)
  Api-Module/src/docs/asciidoc/StrongPoint.adoc
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/UserSecurityUtil.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/application/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/dto/CreateStrongPoint.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/service/StrongPointCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/.gitkeep
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/repository/StrongPointRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/aggregate/StrongPoint.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/exception/StrongPointException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/repository/StrongPointRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/aggregate/Tag.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/ExperienceRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/ExperienceRepositoryImpl.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceContentJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceStrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceTagJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/repository/StrongPointJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceContentMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceContentMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/StrongPointMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/TagMapper.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/StrongPointRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/jpa/entity/StrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/jpa/repository/StrongPointJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/mapper/StrongPointMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/jpa/entity/TagJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/jpa/repository/TagJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/mapper/TagMapper.java
  gradlew
Labels: ✨ Feature, 🦦 용현

#58 feat: 상위 & 하위 태그 등록 API 구현(#52)(#44)
  Api-Module/src/docs/asciidoc/Tag.adoc
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/service/StrongPointCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/dto/CreateTag.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/service/TagCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/service/TagDeleteService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointControllerTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagControllerTest.kt
  Domain-Module/.jqwik-database
  Domain-Module/build.gradle.kts
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/common/entity/DomainEntity.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/repository/StrongPointRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/repository/StrongPointRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/aggregate/Tag.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/exception/TagException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/repository/TagRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagRemover.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/tag/TagTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/StrongPointRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/TagRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/jpa/repository/TagJpaRepository.java
Labels: ✨ Feature, 🦦 용현

#60 feat: JD 등록, 자소서 등록 API 구현(#56)
  .github/workflows/CI-dev.yml
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/docs/asciidoc/User.adoc
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/CreateApply.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/CreateApplyContent.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/CreateJobDescription.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/config/SecurityConfig.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/JobDescriptionCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthControllerTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserControllerTest.kt
  Api-Module/src/testFixtures/kotlin/com/bamyanggang/apimodule/BaseRestDocsTest.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/ExceptionHandler.kt
  Domain-Module/build.gradle.kts
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/Apply.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/ApplyContent.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescription.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/enums/WriteStatus.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/ApplyContentRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/ApplyRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/JobDescriptionRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyContentAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionAppender.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/aggregate/ApplyContentTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/aggregate/ApplyTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/aggregate/JobDescriptionTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/service/ApplyAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/service/ApplyContentAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/service/JobDescriptionAppenderTest.kt
  Infrastructure-Module/persistence/build.gradle
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/common/UUIDBinaryConverter.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/ApplyContentRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/ApplyRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/JobDescriptionRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/ApplyContentJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/ApplyJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/JobDescriptionJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/ApplyContentJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/ApplyJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/JobDescriptionJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/mapper/JobDescriptionMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/UserJpaEntity.java
  build.gradle.kts
Labels: ✨ Feature, 🐳 세은

#62 refactor : Token 저장 로직 복구
  Api-Module/build.gradle.kts
  Api-Module/src/docs/asciidoc/User.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/ProfileImage.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/ProfileImageGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/security/filter/JwtAuthenticationFilter.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/Token.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/vo/ProfileImage.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/ProfileImageRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/TokenRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/ProfileImageReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenRemover.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/ProfileImageRepositoryImpl.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/TokenRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/ProfileImageJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/TokenJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/ProfileImageJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/TokenJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/mapper/UserMapper.java
  Support-Module/Jwt/build.gradle.kts
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/JwtProvider.kt
Labels: 🔨 Refactor, 🐳 세은

#66 refactor : 소셜 로그인 응답값 변경
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/UserInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/UserInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/AuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/impl/GoogleOAuthHandler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/impl/KakaoOAuthHandler.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/UserControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/User.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserAppender.kt
  Infrastructure-Module/client/src/main/kotlin/com/bamyanggang/client/KakaoOAuthClient.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/entity/UserJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/mapper/UserMapper.java
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/PrivateClaims.kt
Labels: 🔨 Refactor, 🐳 세은

#71 refactor: 자기소개서 등록 API 요청 필드 수정
  Api-Module/.jqwik-database
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/CreateApply.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyCreateService.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/.jqwik-database
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/Apply.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyAppender.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/aggregate/ApplyTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/service/ApplyAppenderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/ApplyJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/mapper/JobDescriptionMapper.java
Labels: 🔨 Refactor, 🐳 세은

#68 feat: 경험 등록 API 구현(#39)
  Api-Module/.jqwik-database
  Api-Module/src/docs/asciidoc/Experience.adoc
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/application/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/application/dto/CreateExperience.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/application/service/ExperienceCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/.gitkeep
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/ExperienceApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/ExperienceController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/service/StrongPointCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointController.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/service/TagCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/service/TagDeleteService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/ExperienceControllerTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/Experience.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/ExperienceContent.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/repository/ExperienceContentRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/repository/ExperienceRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceContentAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/aggregate/StrongPoint.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/repository/StrongPointRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/aggregate/Tag.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/repository/TagRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagReader.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/ExperienceTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/aggregate/ApplyTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/common/UUIDBinaryConverter.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/ExperienceContentImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/ExperienceRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceContentJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceStrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/jpa/entity/ExperienceTagJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceContentMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/StrongPointRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/jpa/entity/StrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/TagRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/jpa/entity/TagJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/mapper/TagMapper.java
  Infrastructure-Module/persistence/src/main/resources/application-db.yml
Labels: ✨ Feature, 🦦 용현

#59 feat: 역량 키워드 조회 & 삭제 API 구현(#47)
  Api-Module/src/docs/asciidoc/StrongPoint.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/dto/GetStrongPoint.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/service/StrongPointCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/service/StrongPointDeleteService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/service/StrongPointGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/strongpoint/application/StrongPointCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/strongpoint/presentation/StrongPointControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/aggregate/StrongPoint.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/exception/StrongPointException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/exception/StrongPointExceptionMessage.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/repository/StrongPointRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointRemover.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/aggregate/StrongPointTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointReaderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/StrongPointRepositoryImpl.java
Labels: ✨ Feature, 🦦 용현

#77 feat: JD 조회 API 구현
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/dto/SliceResponse.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/GetJobDescriptionInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/common/pagination/SliceDomain.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescription.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/enums/SortType.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/enums/WriteStatus.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/ApplyRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/JobDescriptionRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionReader.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/ApplyRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/JobDescriptionRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/ApplyJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/JobDescriptionJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/TokenRepositoryImpl.java
Labels: ✨ Feature, 🐳 세은

#81 feat : JD 공고 조회 필터링 기능 추가
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/dto/PageResponse.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/common/dto/SliceResponse.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Common-Module/src/testFixtures/kotlin/com/bamyanggang/commonmodule/fixture/FixtureMonkeyUtils.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/common/pagination/PageDomain.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/Apply.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescription.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/JobDescriptionRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionModifier.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionReader.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/jobDescription/aggregate/ApplyTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/JobDescriptionRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/ApplyJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/JobDescriptionJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/JobDescriptionJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/mapper/JobDescriptionMapper.java
Labels: ✨ Feature, 🐳 세은

#96 refactor : Apply, ApplyContent 도메인 설계 수정
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyCreateService.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/Apply.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/ApplyContent.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyContentAppender.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/ApplyContentTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/ApplyTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyContentAppenderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/ApplyContentRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/ApplyContentJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/entity/ApplyJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/ApplyContentJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/mapper/JobDescriptionMapper.java
Labels: 🔨 Refactor, 🐳 세은

#97 feat: 자기소개서 상세 조회 API 구현
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/GetApplyInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/GetJobDescriptionInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplicationInfoGetServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/ApplyRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyReader.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyReaderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/ApplyRepositoryImpl.java
Labels: ✨ Feature, 🐳 세은

#98 feat: 자기소개서 수정 API 구현
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/ApplyInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/CreateApply.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/CreateApplyContent.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyUpdateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/Apply.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyModifier.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/ApplyTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyModifierTest.kt
Labels: ✨ Feature, 🐳 세은

#99 feat : JD 작성 상태 변경 API 구현
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/JobDescriptionUpdateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescription.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/exception/JobDescriptionException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionModifier.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescriptionTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionModifierTest.kt
Labels: ✨ Feature, 🐳 세은

#104 feat : JD 수정 API 구현
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/ApplyInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/JobDescriptionInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyCreateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/ApplyUpdateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/JobDescriptionCreateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/JobDescriptionUpdateServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescription.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionModifier.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/aggregate/JobDescriptionTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionModifierTest.kt
Labels: ✨ Feature, 🐳 세은

#106 feat : JD 삭제 API 구현
  Api-Module/src/docs/asciidoc/JobDescription.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyInfoGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/ApplyUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionDeleteService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/JobDescriptionDeleteServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/JobDescriptionRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionRemover.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionRemoverTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/JobDescriptionRepositoryImpl.java
Labels: ✨ Feature, 🐳 세은

#109 feat: 북마크 API 구현
  Api-Module/src/docs/asciidoc/BookMark.adoc
  Api-Module/src/docs/asciidoc/index.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/bookmark/application/BookmarkService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/bookmark/presentation/BookmarkApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/bookmark/presentation/BookmarkController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/bookmark/application/BookmarkServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/bookmark/presentation/BookmarkControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/bookmark/aggregate/Bookmark.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/bookmark/enums/BookmarkStatus.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/bookmark/repository/BookmarkRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/bookmark/service/BookmarkAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/bookmark/service/BookmarkModifier.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/bookmark/service/BookmarkReader.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/bookmark/aggregate/BookmarkTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/bookmark/service/BookmarkAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/bookmark/service/BookmarkModifierTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/bookmark/service/BookmarkReaderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/bookmark/BookmarkRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/bookmark/jpa/entity/BookmarkJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/bookmark/jpa/repository/BookmarkJpaRepository.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/bookmark/mapper/BookmarkMapper.java
Labels: ✨ Feature, 🐳 세은

#110 refactor : 로그아웃 API 요청 형식 변경
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/dto/Logout.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthApi.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/user/presentation/AuthControllerTest.kt
Labels: 🔨 Refactor, 🐳 세은

#120 feat : JD 상태 변경 스케쥴러 구현
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoUpdateService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/scheduler/UpdateWriteStatusScheduler.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/global/config/SchedulerConfig.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/JobDescriptionRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionModifier.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/JobDescriptionRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/JobDescriptionJpaRepository.java
Labels: ✨ Feature, 🐳 세은

#129 refactor : 마감순 정렬 로직 수정(#128)
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/JobDescriptionRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/JobDescriptionReader.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/JobDescriptionRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/JobDescriptionJpaRepository.java
Labels: 🔨 Refactor, 🐳 세은

#133 refactor : 도메인 모듈 web 의존성 제거
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/bookmark/config/BookmarkServiceConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/config/ExperienceServiceConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/config/JobDescriptionServiceConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/strongpoint/config/StrongPointServiceConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/config/TagServiceConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/exception/AuthException.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/config/UserServiceConfiguration.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagControllerTest.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/CustomException.kt
  Common-Module/src/main/kotlin/com/bamyanggang/commonmodule/exception/ExceptionHandler.kt
  Domain-Module/build.gradle.kts
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceModifier.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceRemover.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/exception/JobDescriptionException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/exception/StrongPointException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointRemover.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/exception/TagException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/service/TagRemover.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/Token.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/User.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/common/exception/PersistenceException.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/mapper/UserMapper.java
  Support-Module/Jwt/src/main/kotlin/com/bamyanggang/jwt/exception/JwtException.kt
Labels: 🔨 Refactor, 🐳 세은

#143 feat:북마크 경험 태그 필터링 API 구현(#127)
  Api-Module/src/docs/asciidoc/Experience.adoc
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/application/service/ExperienceGetService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/ExperienceController.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/experience/presentation/ExperienceControllerTest.kt
Labels: ✨ Feature, 🦦 용현

#146 refactor : 토큰 로직 수정(#145)
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/AuthService.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/AuthHandlerManager.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/application/service/handler/config/AuthHandlerConfiguration.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/user/config/UserServiceConfiguration.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/Token.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/TokenRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenAppender.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenModifier.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenReader.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenRemover.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/TokenRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/TokenJpaRepository.java
Labels: 🔨 Refactor, 🐳 세은

#153 refactor: 태그, 역량 키워드, 경험 매퍼 클래스 객체 생성 방식 리팩토링
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/presentation/TagController.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/Experience.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/ExperienceStrongPoint.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/aggregate/StrongPoint.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/tag/aggregate/Tag.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/experience/mapper/ExperienceMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/jpa/entity/StrongPointJpaEntity.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/strongpoint/mapper/StrongPointMapper.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/tag/mapper/TagMapper.java
Labels: 🔨 Refactor, 🦦 용현

#158 refactor : JD 상세정보 조회 응답값 수정
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/dto/JobDescriptionInfo.kt
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/service/JobDescriptionInfoGetService.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/application/JobDescriptionInfoGetServiceTest.kt
  Api-Module/src/test/kotlin/com/bamyanggang/apimodule/domain/jobDescription/presentation/JobDescriptionControllerTest.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/repository/ApplyRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyReader.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/jobDescription/service/ApplyReaderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/ApplyRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/jobDescription/jpa/repository/ApplyJpaRepository.java
Labels: 🔨 Refactor, 🐳 세은

#161 refactor : 회원가입 로직 수정
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/exception/UserException.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/repository/UserRepository.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserAppender.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserAppenderTest.kt
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/UserRepositoryImpl.java
  Infrastructure-Module/persistence/src/main/java/com/bamyanggang/persistence/user/jpa/repository/UserJpaRepository.java
Labels: 🔨 Refactor, 🐳 세은

#162 test: Token, User 도메인 테스트 코드 작성(#132)
  Common-Module/src/testFixtures/kotlin/com/bamyanggang/commonmodule/fixture/FixtureMonkeyUtils.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenRemover.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/TokenTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/aggregate/UserTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenModifierTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/service/TokenRemoverTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserModifierTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/user/service/UserReaderTest.kt
  Support-Module/Jwt/src/test/kotlin/com/bamyanggang/jwt/TokenProviderTest.kt
  Support-Module/cache/src/test/kotlin/com/bamyanggang/cache/CacheManagerTest.kt
  Support-Module/lock/src/test/kotlin/com/bamyanggang/lock/LockManagerTest.kt
Labels: ✅ Test, 🐳 세은

#170 test: 경험 도메인 테스트 코드 작성(#169)
  Api-Module/src/main/kotlin/com/bamyanggang/apimodule/domain/tag/application/service/TagDeleteService.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/Experience.kt
  Domain-Module/src/main/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceReader.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/experience/aggregate/ExperienceTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceModifierTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceReaderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/experience/service/ExperienceRemoverTest.kt
Labels: ✅ Test, 🦦 용현

#168 test: 역량 키워드 도메인 테스트 코드 작성(#165)
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/aggregate/StrongPointTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/KeywordReaderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointAppenderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointReaderTest.kt
  Domain-Module/src/test/kotlin/com/bamyanggang/domainmodule/domain/strongpoint/service/StrongPointRemoverTest.kt
Labels: ✅ Test, 🦦 용현
